### ISSUE TITLE
从 pypi 寻来, 敢问有兴趣参与木兰重现项目吗?

### ISSUE THREAD

**Issue by nobodxbodon** [Ailln/python-package-template#1]
好像在你的[知乎回答](https://www.zhihu.com/question/366509495/answer/977632643)同时建了 pypi 上的 [ulang 库](https://pypi.org/project/ulang/).  如有打算将木兰继续下去, 不妨到[重现项目](https://gitee.com/MulanRevive/mulan-rework)一聚?

**Comment by Ailln** [comment]
暂无

**Comment by nobodxbodon** [comment]
那么请问 ulang 和 mulan 两个库有何打算？应该是因木兰风波而创吧？

**Comment by Ailln** [comment]
@nobodxbodon 给我你的 pypi 的 username，我把 ulang 送给你。

**Comment by nobodxbodon** [comment]
xuanwu
在考虑用 ulang 代替现在的 [mulang 包](https://pypi.org/project/mulang/)。
欢迎任何意见建议。
谢谢。

**Comment by nobodxbodon** [comment]
刚发布了 ulang 0.0.14.1。如有不妥请告知。谢谢。

**Comment by Ailln** [comment]
没关系，你是 owner 了。你可以把我的账号移除吗？我发现无法自己退出。

**Comment by nobodxbodon** [comment]
我是希望有第二个 owner，以备不时之需。
如果没带来什么不便，可否暂时保留？

**Comment by Ailln** [comment]
我暂时不会参与进来，有这样的权限不太合适。

你可以邀请其他参与的作者进来，成为 owner ～

**Comment by nobodxbodon** [comment]
好吧，刚移除了。
感谢支持，随时恭候。

**Comment by Ailln** [comment]
好的。

**Comment by nobodxbodon** [comment]
一些进展报告，年初的小结：[木兰编程语言一岁了！](https://zhuanlan.zhihu.com/p/345851006)
刚写的简报：[木兰语言 0.0.21 查缺补漏；rply 改进、接口中文化](https://zhuanlan.zhihu.com/p/388440048)
